#!/usr/bin/env bash

which rustup >/dev/null 2>&1 || curl https://sh.rustup.rs -sSf | sh

rustup update
rustup self update

rustup install nightly
rustup default nightly
rustup component add rustfmt
rustup component add clippy

rustup default stable
rustup component add rustfmt
rustup component add clippy

