#!/bin/bash

FILENAME="/etc/hosts"

printf "
127.0.0.1	localhost
127.0.1.1	chris-thinkpad
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

" | sudo tee "$FILENAME" >/dev/null

curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | grep '^0.0.0.0' | sudo tee -a "$FILENAME" >/dev/null

