#!/bin/bash

# Remove any previous URLs redirected to 0.0.0.0 and
# then fetch a fresh copy of the StevenBlack hosts file
# and remove any lines from it that do not redirect
# to 0.0.0.0 and append it to the cleaned /etc/hosts

grep -vP '^0.0.0.0 ' /etc/hosts | \
  sudo tee /etc/hosts >/dev/null && \
  curl -s https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | \
  grep '^0.0.0.0 ' | \
  sudo tee -a /etc/hosts >/dev/null

