#!/usr/bin/env bash

#
# See: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
#

cd ~/Download

# Add Microsoft package signing key to list of trusted keys and add package repository

wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

sudo dpkg -i packages-microsoft-prod.deb

# Install the SDK

sudo apt update && sudo apt install -y apt-transport-https && sudo apt update && sudo apt install -y dotnet-sdk-5.0

# Install the runtime

sudo apt update && sudo apt install -y apt-transport-https && sudo apt update && sudo apt install -y aspnetcore-runtime-5.0


